apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-group-sync
  namespace: group-sync-operator
spec:
  secretStoreRef:
{% if cluster.access_type == "admin" %}
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
{% else %}
    name: nerc-secret-store
    kind: SecretStore
{% endif %}
  target:
    name: github-group-sync
  data:
  - secretKey: appId
    remoteRef:
      key: nerc/{{ cluster.name }}/group-sync-operator/github-group-sync-token
      property: appId
  - secretKey: privateKey
    remoteRef:
      key: nerc/{{ cluster.name }}/group-sync-operator/github-group-sync-token
      property: privateKey