apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
{% if cluster.access_type == "admin" %}
- ../../bundles/nerc-certificate-clusterissuers
- ../../bundles/external-secrets-clustersecretstore
{% endif %}
- ../../bundles/node-feature-discovery
- ../../bundles/patch-operator
- ../../bundles/clusterissuer-http01
- ../../base/rbac.authorization.k8s.io/clusterroles/allow-edit-rbac
- ../../base/core/namespaces/openshift-gitops
- externalsecrets
- issuers
- feature/odf
- machineconfigs/configure-bond0
- certificates
- nodenetworkconfigurationpolicies
{% if cluster.access_type == "public" %}
- secretstores
{% endif %}

components:
{% if "keycloak" in cluster.oauth %}
  {{keycloakcomponent}}
{% endif %}
{% if "github" in cluster.oauth %}
  {{githubcomponent}}
{% endif %}

  # this must come last in order to apply
  # to all resources.
  - ../../components/argocd-skip-dryrun

generatorOptions:
  disableNameSuffixHash: true
  
patches:
{% if "keycloak" in cluster.oauth %}
{{keycloakpatch}}
{% endif %} 
{% if "github" in cluster.oauth %}
{{githubpatch}}
{% endif %}
{% if cluster.access_type == "public" %}
- target:
    kind: SecretStore
  patch: |
    - op: replace
      path: /spec/provider/vault/auth/kubernetes/mountPath
      value: kubernetes/{{ cluster.name }}
{% endif %}
- target:
    kind: ExternalSecret
    name: aws-route53-credentials
  patch: |
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: nerc/{{ cluster.name }}/aws-route53-credentials
- target:
    kind: APIServer
    name: cluster
  patch: |
    - op: replace
      path: /spec/servingCerts/namedCertificates/0/names/0
      value: api.{{ cluster.name }}.nerc.mghpcc.org
{% if cluster.access_type == "admin" %}
- patch: |
    apiVersion: external-secrets.io/v1beta1
    kind: ClusterSecretStore
    metadata:
      name: nerc-cluster-secrets
    spec:
      provider:
        vault:
          auth:
            kubernetes:
              mountPath: kubernetes/nerc-ocp-obs
          server: https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/
{% endif %}
- target:
    kind: Issuer
    name: letsencrypt-.*-dns01
  patch: |
    - op: replace
      path: /spec/acme/solvers/0/selector/dnsZones
      value:
        - {{ cluster.name }}.nerc.mghpcc.org