apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/external-secrets-clustersecretstore
- ../../base/core/namespaces/dex
- feature/odf
- clusterversion.yaml
- externalsecrets
- nodenetworkconfigurationpolicies

components:
{% if "keycloak" in cluster.oauth %}
  {{keycloakcomponent}}
{% endif %}
{% if "github" in cluster.oauth %}
  {{githubcomponent}}
{% endif %}

  # this must come last in order to apply
  # to all resources.
  - ../../components/argocd-skip-dryrun

generatorOptions:
  disableNameSuffixHash: true

patches:
- path: features/odf/storageclasses/ocs-external-storagecluster-ceph-rbd_patch.yaml
- path: clustersecretstores/nerc-cluster-secrets_patch.yaml
{% if "keycloak" in cluster.oauth %}
{{keycloakpatch}}
{% endif %}
{% if "github" in cluster.oauth %}
{{githubpatch}}
{% endif %}
- target:
    kind: APIServer
    name: cluster
  patch: |
    - op: replace
      path: /spec/servingCerts/namedCertificates/0/names/0
      value: api.{{ cluster.name }}.rc.fas.harvard.edu