apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-api-certificate
  namespace: openshift-config
spec:
  issuerRef:
    name: letsencrypt-production-dns01
{% if cluster.access_type == "public" %}
    kind: Issuer
{% else %}
    kind: ClusterIssuer
{% endif %}
  secretName: default-api-certificate
  duration: {{ cluster.apiCertDuration|default('2160h0m0s',true) }}
  renewBefore: {{ cluster.apiCertRenewBefore|default('360h0m0s',true) }}
  dnsNames:
    - "{{ cluster.apiCertDnsName }}"