clusters:
  - name: #Name of the cluster
    address_type: #external or internal
    access_type: #admin or public
    oauth: #Options list: [keycloak,github] or [keycloak] or [github]
    githubClientID: 
    keycloakClientID:
    cephstoragePool: #for ocs external storage cluster
    apiCertDuration: #2160h0m0s
    apiCertRenewBefore: #360h0m0s
    apiCertDnsName:
    ingressCertDuration: #2160h0m0s
    ingressCertRenewBefore: #360h0m0s
    ingressCertDnsName:
