apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan-{{ cluster.vlanID }}-nese
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
    - name: bond0.{{ cluster.vlanID }}
      type: vlan
      state: up
      ipv4:
        enabled: true
        dhcp: true
        auto-routes: true
      vlan:
        base-iface: bond0
        id: {{ cluster.vlanID }}
      mtu: 9000
