apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-ceph-external-cluster-details
  namespace: openshift-storage
spec:
  secretStoreRef:
{% if cluster.access_type == "admin" %}
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
{% else %}
    name: nerc-secret-store
    kind: SecretStore
{% endif %}
  target:
    name: rook-ceph-external-cluster-details
  data:
  - secretKey: external_cluster_details
    remoteRef:
      key: nerc/{{ cluster.name }}/openshift-storage/rook-ceph-external-cluster-details
      property: external_cluster_details
