output_directory: output/{{ cluster.name }}
keycloakcomponent: '- ../../components/nerc-oauth-keycloak'
githubcomponent: '- ../../components/nerc-oauth-github'
githubpatch: |
  - patch: |
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec:
        identityProviders:
        - name: github
          github:
            clientID: {{ cluster.githubClientID }}
  - target:
      kind: ExternalSecret
      name: github-client-secret
    patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: nerc/{{ cluster.name }}/openshift-config/github-client-secret
keycloakpatch: |
  - patch: |
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec:
        identityProviders:
        - name: mss-keycloak
          openID:
            clientID: {{ cluster.keycloakClientID }}
internal: |
  - target:
      kind: ExternalSecret
    patch: |
      - op: replace
        path: /spec/secretStoreRef
        value:
          kind: ClusterSecretStore
          name: nerc-cluster-secrets